package one;
// Generated Jun 6, 2018 2:12:10 PM by Hibernate Tools 4.3.1



/**
 * Studentdetails generated by hbm2java
 */
public class Studentdetails  implements java.io.Serializable {


     private int sid;
     private String name;

    public Studentdetails() {
    }

    public Studentdetails(int sid, String name) {
       this.sid = sid;
       this.name = name;
    }
   
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


